[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "build"

  [plugins.inputs.policies]
    workerSrc = "'blob:'"
    connectSrc = "https://*.stripe.com"
    frameSrc = "https://*.stripe.com"
    scriptSrc = "https://*.stripe.com"
