[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
    default-src *  data: blob: filesystem: about: ws: wss: 'unsafe-inline' 'unsafe-eval' 'unsafe-dynamic';
    script-src * data: blob: 'unsafe-inline' 'unsafe-eval';
    connect-src * data: blob: 'unsafe-inline';
    img-src * data: blob: 'unsafe-inline';
    frame-src * data: blob: ;
    worker-src * data: blog: ;
    style-src * data: blob: 'unsafe-inline';
    font-src * data: blob: 'unsafe-inline'; ;'''
