[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
    default-src 'blob:' ;
    child-src 'blob:' ;
    img-src 'data:' 'blob:' ;
    connect-src https://*.tiles.mapbox.com https://api.mapbox.com https://events.mapbox.com ;'''
