[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "build"

  [plugins.inputs.policies]
    connectSrc = "https://*.stripe.com"
    frameSrc = "https://*.stripe.com"
    scriptSrc = "https://*.stripe.com"
    worker-src = "'blob:'"
    child-src = "'blob:'"
    img-src data = "'blob:'"
    connect-src = "https://*.tiles.mapbox.com https://api.mapbox.com https://events.mapbox.com"
