export const ORG_REGISTER_REQUEST = 'ORG_REGISTER_REQUEST';
export const ORG_REGISTER_SUCCESS = 'ORG_REGISTER_SUCCESS';
export const ORG_REGISTER_FAIL = 'ORG_REGISTER_FAIL';

export const LIST_ORG_REQUEST = 'LIST_ORG_REQUEST';
export const LIST_ORG_SUCCESS = 'LIST_ORG_SUCCESS';
export const LIST_ORG_FAIL = 'LIST_ORG_FAIL';

export const MY_ORG_LIST_REQUEST = 'MY_ORG_LIST_REQUEST';
export const MY_ORG_LIST_SUCCESS = 'MY_ORG_LIST_SUCCESS';
export const MY_ORG_LIST_FAIL = 'MY_ORG_LIST_FAIL';

export const REMOVE_ORG_REQUEST = 'REMOVE_ORG_REQUEST';
export const REMOVE_ORG_SUCCESS = 'REMOVE_ORG_SUCCESS';
export const REMOVE_ORG_FAIL = 'REMOVE_ORG_FAIL';

export const GET_ORG_REQUEST = 'GET_ORG_REQUEST';
export const GET_ORG_SUCCESS = 'GET_ORG_SUCCESS';
export const GET_ORG_FAIL = 'GET_ORG_FAIL';
