export const PANTRY_REGISTER_REQUEST = 'PANTRY_REGISTER_REQUEST';
export const PANTRY_REGISTER_SUCCESS = 'PANTRY_REGISTER_SUCCESS';
export const PANTRY_REGISTER_FAIL = 'PANTRY_REGISTER_FAIL';

export const LIST_PANTRY_REQUEST = 'LIST_PANTRY_REQUEST';
export const LIST_PANTRY_SUCCESS = 'LIST_PANTRY_SUCCESS';
export const LIST_PANTRY_FAIL = 'LIST_PANTRY_FAIL';