export const LIST_PANTRY_REQUEST = 'LIST_PANTRY_REQUEST';
export const LIST_PANTRY_SUCCESS = 'LIST_PANTRY_SUCCESS';
export const LIST_PANTRY_FAIL = 'LIST_PANTRY_FAIL';

export const MY_PANTRY_LIST_REQUEST = 'MY_PANTRY_LIST_REQUEST';
export const MY_PANTRY_LIST_SUCCESS = 'MY_PANTRY_LIST_SUCCESS';
export const MY_PANTRY_LIST_FAIL = 'MY_PANTRY_LIST_FAIL';

export const PANTRY_REGISTER_REQUEST = 'PANTRY_REGISTER_REQUEST';
export const PANTRY_REGISTER_SUCCESS = 'PANTRY_REGISTER_SUCCESS';
export const PANTRY_REGISTER_FAIL = 'PANTRY_REGISTER_FAIL';

export const PANTRY_UPDATE_REQUEST = 'PANTRY_UPDATE_REQUEST';
export const PANTRY_UPDATE_SUCCESS = 'PANTRY_UPDATE_SUCCESS';
export const PANTRY_UPDATE_FAIL = 'PANTRY_UPDATE_FAIL';

export const SINGLE_PANTRY_LIST_REQUEST = 'SINGLE_PANTRY_LIST_REQUEST';
export const SINGLE_PANTRY_LIST_SUCCESS = 'SINGLE_PANTRY_LIST_SUCCESS';
export const SINGLE_PANTRY_LIST_FAIL = 'SINGLE_PANTRY_LIST_FAIL';
