export const LIST_DONATE_REQUEST = 'LIST_DONATE_REQUEST';
export const LIST_DONATE_FAIL = 'LIST_DONATE_FAIL';
export const LIST_DONATE_SUCCESS = 'LIST_DONATE_SUCCESS';

export const USER_DONATE_REQUEST = 'USER_DONATE_REQUEST';
export const USER_DONATE_FAIL = 'USER_DONATE_FAIL';
export const USER_DONATE_SUCCESS = 'USER_DONATE_SUCCESS';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';
<<<<<<< Updated upstream
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
=======
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
>>>>>>> Stashed changes
